In [ ]:
#Experiment 9
#tools for EDA - study of numpy library
#name- divij bhandari
#prn 25070123160

In [ ]:
#declaration of numpy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
a.shape

(7,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#in built functions using numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [12]:
print(b * 2)
print(a + 5)


[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [13]:
#Dimension of array
print(a.ndim)

1


In [15]:
np.mean(a)

np.float64(93.0)

In [16]:
np.median(a)

np.float64(30.0)

In [17]:
np.max(a)

np.int64(500)

In [18]:
np.min(a)

np.int64(1)

In [19]:
np.sum(a)

np.int64(651)